{"name": "test_TC_003_user_сan_autorize[locked_out_user-secret_sauce]", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: wrong url", "trace": "self = <SauceDemoProject.tests.test_TC_003_user_can_be_autorize.TestSample object at 0x0000025BE2D3F460>\nd = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d41e514b8220ca041e0daf8257bf2e0a\")>\nusername = 'locked_out_user', password = 'secret_sauce'\n\n    @pytest.mark.parametrize(\n        \"username, password\",\n        [\n            (\"standard_user\", \"secret_sauce\"),\n            (\"performance_glitch_user\", \"secret_sauce\"),\n            (\"problem_user\", \"secret_sauce\"),\n            pytest.param(\n                \"locked_out_user\",\n                \"secret_sauce\",\n                marks=pytest.mark.xfail(raises=AssertionError),\n            ),\n        ],\n    )\n    def test_TC_003_user_сan_autorize(self, d, username, password):\n        link = \"https://www.saucedemo.com/\"\n        page = LoginPage(d, link)\n        page.open_page()\n        page.register_user(username, password)\n        time.sleep(2)\n        link = \"https://www.saucedemo.com/inventory.html\"\n        page = ProductsPage(d, link)\n>       page.should_be_products_page()\n\ntest_TC_003_user_can_be_autorize.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\products_page.py:13: in should_be_products_page\n    self.should_be_link(ProductsPageSrc.LINK)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.products_page.ProductsPage object at 0x0000025BE2D57100>\nlink = 'inventory'\n\n    def should_be_link(self, link):\n>       assert link in self.browser.current_url, \"wrong url\"\nE       AssertionError: wrong url\n\n..\\pages\\base_page.py:59: AssertionError"}, "attachments": [{"name": "Screeshot", "source": "b88e5a91-58c9-4433-ac6b-8764d13e2026-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "855c0512-3126-4390-b6eb-4b26497bdd85-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'locked_out_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1669806982118, "stop": 1669806984383, "uuid": "86824b53-9727-488e-addd-8e1401f23c3d", "historyId": "14fec9e14c2eabd56f61c502cf39b536", "testCaseId": "58098719add8c8f75a04510e5eb59a4a", "fullName": "tests.test_TC_003_user_can_be_autorize.TestSample#test_TC_003_user_сan_autorize", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(raises=<class 'AssertionError'>)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_TC_003_user_can_be_autorize"}, {"name": "subSuite", "value": "TestSample"}, {"name": "host", "value": "DESKTOP-DBCHJ8G"}, {"name": "thread", "value": "16956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_TC_003_user_can_be_autorize"}]}